Creare il file markdown CODE_OF_CONDUCT.md
softeng2223-inf-uniba/progetto2223-nygaard pull request #10
Opened 2023-04-06 09:27 UTC by Fonty02

Ho creato il file markdown CODE_OF_CONDUCT.md

2023-04-06 09:44 UTC, Davy592 requested changes
Per un file più pulito sarebbe meglio utilizzare quanto più possibile i marcatori propri del MarkDown. Per esempio per l'elenco puntato.
A riga 49 introduci una virgola invece di utilizzare due volte la congiunzione "e".

2023-04-06 09:50 UTC, Stefano-Labianca requested changes
A riga 62 andrebbe camnbiato da _colui/lei_ con _colui/colei_, mentre a riga 63 sta scritto _dunque quindi_

2023-04-06 12:09 UTC, GiudittaIzzo requested changes
Necessaria una riformulazione della riga 62. Si potrebbe riformulare nel seguente modo:
"Gli Assignees sono il membro del team che ha creato la issue e il membro del team che l'ha risolta. Una singola persona può aver assunto entrambi i ruoli"

2023-04-06 17:48 UTC, mattiacurri requested changes
Confermo le osservazioni fatte dai colleghi.
Ritengo che alcuni dei punti riportati nel paragrafo "Stile di comunicazione e codice" possano essere divisi tra i paragrafi "Scrittura del codice" e "Regole di pull request", rivedendo il nome di quest'ultimo per prevedere anche le convenzioni stabilite per i commit.
Più in generale, per quanto riguarda le convenzioni per la scrittura del codice, proporrei di valutare l'adozione (totale o parziale) di uno style guide (eg. [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)) in modo da utilizzare linee guide ben definite, previa visione del documento da parte di tutti i colleghi.

2023-04-07 17:07 UTC, Stefano-Labianca approved these changes

2023-04-07 17:50 UTC, Davy592 approved these changes
Il file è completo ed esaustivo, nulla da aggiungere. Non sono presenti errori di sintassi. Ottimo utilizzo della formattazione Markdown

2023-04-07 17:52 UTC, GiudittaIzzo approved these changes
Approvo i cambiamenti

2023-04-08 15:24 UTC, mattiacurri approved these changes
Codice di condotta stilato correttamente

2023-04-08 15:26 UTC, merged