Come giocatore voglio mostrare l'help con elenco comandi
softeng2223-inf-uniba/progetto2223-nygaard pull request #49
Opened 2023-05-08 15:30 UTC by arci-arci

**Criteri di accettazione**
Al comando /help o invocando l'app con flag --help o -h
Il risultato è una descrizione concisa, che normalmente appare all'avvio del programma, seguita dalla lista di comandi disponibili, uno per riga, come da esempio successivo:

- gioca
- esci
- ...

2023-05-08 15:56 UTC, Davy592 requested changes
Tutto sommato il codice redatto è una buona base di partenza ed è effettivamente perfettamente funzionante, ma dovrebbero essere apportate alcune migliorie:

1. Per mantenere una certa coerenza di stile col resto dell'interfaccia utente sarebbe preferibile adottare il titolo "Battaglia Navale" piuttosto che "Battleship" 
2. Per quanto riguarda l'ASCII art del titolo opterei per una Upper Case in modo da enfatizzare maggiormente il titolo stesso
3. Sarebbe bello riuscire a centrare sia l'ASCII art del titolo che quella dell'immagine della nave

2023-05-08 17:21 UTC, mattiacurri requested changes
- Il package `help` lo sposterei nel package `nygaard` invece di tenerlo nel package `game`
- Vi è un package `help` di troppo nel `src`
- La descrizione deve essere concisa e l'help dovrebbe mostrare a schermo solo l'elenco dei comandi con la spiegazione di cosa fa ogni comando, quindi direi di rimuovere le frasi superflue e di tenerle da parte per il manuale utente
- Per lo stesso motivo detto precedentemente, rimuoverei il logo iniziale e lo terrei da parte per essere utilizzato all'avvio del programma

2023-05-08 17:23 UTC, Stefano-Labianca commented
> Il codice redatto è perfettamente funzionante. L'unica modifica da applicare è quella di rimuovere la visualizzazione della ASCII art e del titolo in quanto sarebbe più giusto mostrarle in automatico ad ogni avvio del programma.

Si effettivamente l'ASCII art starebbe molto meglio all'interno di un file apposito e di mostrarla in automatico all'avvio
programma

2023-05-08 17:34 UTC, Stefano-Labianca commented
> * Il package `help` lo sposterei nel package `nygaard` invece di tenerlo nel package `game`
> 
>     * Vi è un package `help` di troppo nel `src`
> 
>     * La descrizione deve essere concisa e l'help dovrebbe mostrare a schermo solo l'elenco dei comandi con la spiegazione di cosa fa ogni comando, quindi direi di rimuovere le frasi superflue e di tenerle da parte per il manuale utente
> 
>     * Per lo stesso motivo detto precedentemente, rimuoverei il logo iniziale e lo terrei da parte per essere utilizzato all'avvio del programma

Non mi ero reso conto di aver lasciato un file di testo 
di troppo, grazie per avermelo fatto notare.

Per la descrizione avevo pensato ad una vera e propria
guida per il giocatore che potesse spiegare il suo ruolo
e quello dell'avversario, ma effettivamente stona molto
rispetto a ciò che si vuole fare con il comando di `/help`.

Infine sulla posizione del file *help.txt* hai 
ragione, andrebbe messa in una directory dedicata e non
all'interno di *game*

2023-05-08 17:47 UTC, Davy592 commented
@Stefano-Labianca @mattiacurri se siete d'accordo con me io direi di provvedere alla creazione del file contenente il logo ed alla sua stampa ad inizio programma in un issue a parte. Questo per mantenere il focus di questo issue/pull request sul singolo comando /help.

2023-05-08 17:52 UTC, mattiacurri commented
> @Stefano-Labianca @mattiacurri se siete d'accordo con me io direi di provvedere alla creazione del file contenente il logo ed alla sua stampa ad inizio programma in un issue a parte. Questo per mantenere il focus di questo issue/pull request sul singolo comando /help.

Sono d'accordo

2023-05-08 17:54 UTC, Stefano-Labianca commented
> @Stefano-Labianca @mattiacurri se siete d'accordo con me io direi di provvedere alla creazione del file contenente il logo ed alla sua stampa ad inizio programma in un issue a parte. Questo per mantenere il focus di questo issue/pull request sul singolo comando /help.

Si sono d'accordo con questa scelta

2023-05-08 18:40 UTC, Stefano-Labianca commented
Ho aggiornato il branch con le modifiche che mi avete richiesto

2023-05-08 20:21 UTC, Davy592 requested changes
Segnalo qualche imprecisione nel codice redatto:
1. manca il JavaDoc per quanto riguarda la costante `DESCRIPTION_PATH`
2. per mantenere una certa coerenza tra i nomi dei metodi direi di rinominare il metodo `fileReader`. Suggerisco di chiamarlo `printFile`
3. nel JavaDoc di suddetto metodo non si fa riferimento al fatto che questo metodo stampi il file letto

2023-05-09 09:56 UTC, Stefano-Labianca commented
> Segnalo qualche imprecisione nel codice redatto:
> 
>     1. manca il JavaDoc per quanto riguarda la costante `DESCRIPTION_PATH`
> 
>     2. per mantenere una certa coerenza tra i nomi dei metodi direi di rinominare il metodo `fileReader`. Suggerisco di chiamarlo `printFile`
> 
>     3. nel JavaDoc di suddetto metodo non si fa riferimento al fatto che questo metodo stampi il file letto

Ho apportato i cambiamenti richiesti, grazie per avermi fatto notare queste sviste

2023-05-09 20:32 UTC, mattiacurri approved these changes
Il codice e le modifiche richieste sono state implementate correttamente

2023-05-09 20:33 UTC, mattiacurri commented
@Stefano-Labianca ti occupi tu di risolvere il merge conflict in modo da fare il merge del branch nel main?

2023-05-10 09:42 UTC, merged